ComedoresEspol/ComedoresEspol/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from FoodFinder import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^FoodFinder/', include('FoodFinder.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ComedoresEspol/FoodFinder/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login


app_name = 'FoodFinder'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^photoGallery/', views.galeria, name='galeria'),
    url(r'^comedores-cercanos/', views.comedoresC, name='comedoresC'),
    url(r'^comedoresFacultad/', views.comedoresF, name='comedoresF'),
    url(r'^mejores-platos/', views.mejoresPlatos, name='mejoresPlatos'),
    url(r'^about/', views.about, name='about'),
    url(r'^time/', views.historia, name='historia'),
    url(r'^login/', views.loginUser, name='login'),
    url(r'^contacto/',views.contacto,name='contacto'),
    url(r'^refresh/$', views.ajaxMejoresPlatos, name='ajaxPlatos'),
    url(r'^valorar/$', views.ajaxValorar, name='ajaxValorar'),
    url(r'^valoracion/$', views.valoracion, name='valoracion'),
    url(r'^denuncia/$', views.denuncia, name='denuncia'),
    url(r'^guardarDenuncia/$', views.guardarDenuncia, name='guardarDenuncia'),
    url(r'^pruebas/$', views.guardarDenuncia, name='pruebas'),
    url(r'^moderador/$', views.sesionModerador, name='moderador'),
    url(r'^moderador/modificarUsuario$', views.modificarModerador, name='modificarModerador'),
    url(r'^admin/$', views.sesionAdmin, name='admin'),
    url(r'^admin/actualizarInfo$', views.actualizarInfoAdmin, name='actualizarInfo'),
    url(r'^admin/actualizarUbicacion$', views.actualizarUbicacion, name='actualizarUbicacion'),
    url(r'^admin/MenuDelDiaAdmin$', views.MenuDelDiaAdmin, name='MenuDelDiaAdmin'),
    url(r'^admin/estadisticasAdmin$', views.estadisticasAdmin, name='estadisticasAdmin'),
    url(r'^admin/crearPlatillo$', views.crearPlatillo, name='crearPlatillo'),
    url(r'^admin/eliminarPlatillo/(?P<platoId>[0-9]+)$', views.eliminarPlatillo, name='eliminarPlatillo'),
    url(r'^super/$', views.sesionSuper, name='super'),
    url(r'^cliente/$', views.sesionCliente, name='cliente'),
    url(r'^cliente/modificarUsuario$', views.modificar, name='modificarUsuario'),
    url(r'^platillo/(?P<pId>[0-9]+)$', views.platilloInfo, name='platillo'),
    url(r'^comedor/(?P<comId>[0-9]+)$', views.comedorInfo, name='comedor'),
    url(r'^guardarComentario/$', views.guardarComentario, name='guardarComentario'),
    url(r'^modificar/$', views.modificar, name='modificar'),
    url(r'^cerrarSesion/$', views.cerrarSesion, name='cerrarSesion'),
    url(r'^comentarios/$', views.mostrarComentarios, name='comentarios'),
    url(r'^mostrarEditarComentario/(?P<idComen>[0-9]+)$', views.ajaxMostrarEditarComentario, name='mostrarEditarComentario'),
    url(r'^eliminarComentario/(?P<idComen>[0-9]+)$', views.ajaxEliminarComentario, name='eliminarComentario'),
    url(r'^editarComentario/$', views.ajaxEditarComentario, name='editarComentario'),
    url(r'^aceptarComentario/$', views.ajaxAceptarComentario, name='aceptarComentario'),
    url(r'^eliminarUsuario/(?P<UrsPk>[0-9]+)$', views.eliminarUsuario, name='eliminarUsuario'),
    url(r'^eliminarComedor/(?P<ComdrPk>[0-9]+)$', views.eliminarComedor, name='eliminarComedor'),
    url(r'^super/crearUsuario/',views.crearUsuario,name='crearUsuario'),
    url(r'^moderador/usuariosConectados$', views.moderadorUsuariosConectados, name='usuariosConectados'),
]

ComedoresEspol/FoodFinder/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models


# Create your models here.
class Facultad(models.Model):
    nombre=models.CharField(max_length=30)
    logo=models.CharField(max_length=300)

    def __str__(self):
        return 'Facultad: {}'.format(self.nombre)

class Comedor(models.Model):
    facultad=models.ForeignKey(Facultad, on_delete=models.CASCADE)
    nombre=models.CharField(max_length=30)
    tipo=models.CharField(max_length=30)
    descripcion=models.CharField(max_length=300)
    hora_ini=models.TimeField()
    hora_fin=models.TimeField()
    ayudantes=models.BooleanField()
    latitud=models.FloatField(default=0)
    longitud=models.FloatField(default=0)

    def __str__(self):
        return 'Comedor: {}'.format(self.nombre)

class Platillo(models.Model):
    comedor=models.ForeignKey(Comedor, on_delete=models.CASCADE)
    titulo=models.CharField(max_length=30)
    tipo=models.CharField(max_length=30)
    precio=models.FloatField()
    cantidad=models.IntegerField()
    imagen=models.CharField(max_length=500)
    valoracion=models.IntegerField()
    imgPlatillo = models.ImageField(upload_to='fotos', blank=True)

    def __str__(self):
        return 'Platillo: {}'.format(self.titulo)

class Usuario(models.Model):
    facultad=models.ForeignKey(Facultad, on_delete=models.CASCADE,blank=True,null=True)
    comedor=models.ForeignKey(Comedor, on_delete=models.CASCADE,blank=True,null=True)
    nombreUsu=models.CharField(max_length=30,default="carlitos", unique=True)
    nombre=models.CharField(max_length=30)
    apellido=models.CharField(max_length=30,default="suarez")
    correo=models.EmailField(max_length=30)
    tipo=models.CharField(max_length=15, default="cliente")
    online = models.BooleanField(default=False)
    ROLES=(
        ('Estudiante', 'Estudiante'),
        ('Docente', 'Docente'),
        ('Trabajador', 'Trabajador'),
    )
    rol=models.CharField(max_length=10, choices=ROLES, default="Estudiante")


class Denuncia(models.Model):
    usuario=models.ForeignKey(Usuario, on_delete=models.CASCADE,default="1")
    comedor=models.CharField(max_length=30)
    fecha_den=models.DateField()
    denuncia=models.CharField(max_length=1000)

    def __str__(self):
        return 'Denuncia a: {}'.format(self.comedor)

class Timeline(models.Model):
    fecha=models.CharField(max_length=30)
    descp=models.CharField(max_length=200)

    def __str__(self):
        return 'Timeline date: {}'.format(self.fecha)

class Comentario(models.Model):
    usuario=models.ForeignKey(Usuario, on_delete=models.CASCADE)
    comedor=models.ForeignKey(Comedor, on_delete=models.CASCADE)
    comentario=models.CharField(max_length=1000)
    aceptado=models.IntegerField(default=0)

    def __str__(self):
        return 'Comentario: {}'.format(self.comentario)

ComedoresEspol/FoodFinder/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password = forms.CharField(widget = forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username', 'email', 'password']

ComedoresEspol/FoodFinder/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from datetime import date
from FoodFinder.models import *
from django.contrib.auth import authenticate, login, logout
from .forms import UserForm
from django.http import JsonResponse
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.models import User


IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

def index(request):
    template = loader.get_template('FoodFinder/index.html')
    try:
        usuario = Usuario.objects.get(nombreUsu=request.user.username)
    except Usuario.DoesNotExist:
        usuario = None
    platillos = Platillo.objects.all()
    if usuario is not None:
        usuarioValido = usuario
    else:
        return redirect('FoodFinder:login')
    context = {
        'usuario': usuarioValido,
        'platillos':platillos,
    }
    return HttpResponse(template.render(context, request))

def galeria(request):
    template = loader.get_template('FoodFinder/photoGallery.html')
    try:
        usuario = Usuario.objects.get(nombreUsu=request.user.username)
    except Usuario.DoesNotExist:
        usuario = None
    platillos=Platillo.objects.all()
    if usuario is not None:
        usuarioValido = usuario
    else:
        return redirect('FoodFinder:login')
    context = {
        'usuario': usuarioValido,
        'platillos':platillos,
    }
    return HttpResponse(template.render(context, request))

def comedoresC(request):
    template = loader.get_template('FoodFinder/comedores-cercanos.html')
    try:
        usuario = Usuario.objects.get(nombreUsu=request.user.username)
    except Usuario.DoesNotExist:
        usuario = None
    comedores = Comedor.objects.all()
    if usuario is not None:
        usuarioValido = usuario
    else:
        return redirect('FoodFinder:login')
    context = {
        'usuario': usuarioValido,
        'comedores':comedores,
    }
    return HttpResponse(template.render(context, request))

def comedoresF(request):
    template = loader.get_template('FoodFinder/comedoresFacultad.html')
    try:
        usuario = Usuario.objects.get(nombreUsu=request.user.username)
    except Usuario.DoesNotExist:
        usuario = None
    comedores = Comedor.objects.all()
    platillos = Platillo.objects.all()
    facultades = Facultad.objects.all()
    if usuario is not None:
        usuarioValido = usuario
    else:
        return redirect('FoodFinder:login')
    context = {
        'usuario': usuarioValido,
        'comedores': comedores,
        'platillos': platillos,
        'facultades': facultades,
    }
    return HttpResponse(template.render(context, request))

def mejoresPlatos(request):
    template = loader.get_template('FoodFinder/mejores-platos.html')
    try:
        usuario = Usuario.objects.get(nombreUsu=request.user.username)
    except Usuario.DoesNotExist:
        usuario = None
    if usuario is not None:
        usuarioValido = usuario
    else:
        return redirect('FoodFinder:login')
    context = {
        'usuario': usuarioValido,
    }
    return HttpResponse(template.render(context, request))

def about(request):
    template = loader.get_template('FoodFinder/about.html')
    try:
        usuario = Usuario.objects.get(nombreUsu=request.user.username)
    except Usuario.DoesNotExist:
        usuario = None
    if usuario is not None:
        usuarioValido = usuario
    else:
        return redirect('FoodFinder:login')
    context = {
        'usuario': usuarioValido,
    }
    return HttpResponse(template.render(context, request))

def historia(request):
    template = loader.get_template('FoodFinder/time.html')
    historias=Timeline.objects.all()
    try:
        usuario = Usuario.objects.get(nombreUsu=request.user.username)
    except Usuario.DoesNotExist:
        usuario = None
    if usuario is not None:
        usuarioValido = usuario
    else:
        return redirect('FoodFinder:login')
    context = {
        'usuario': usuarioValido,
        "historia":historias,
    }
    return  HttpResponse(template.render(context, request))

def contacto (request):
    template=loader.get_template('FoodFinder/contacto.html')
    email_host=settings.EMAIL_HOST_USER
    try:
        usuario = Usuario.objects.get(nombreUsu=request.user.username)
    except Usuario.DoesNotExist:
        usuario = None
    if usuario is not None:
        usuarioValido = usuario
    else:
        return redirect('FoodFinder:login')
    if(request.method == 'POST'):
        nombres_contacto=  request.POST.get('name')
        correo_contacto=   request.POST.get('email')
        asunto_contacto=   request.POST.get('subject')
        mensaje_contacto=  request.POST.get('message')
        email_envio=[email_host,correo_contacto]
        send_mail(asunto_contacto, mensaje_contacto, email_host ,email_envio, fail_silently=False)
        messages.success(request, 'Gracias por contactarnos!')
    context = {
        'usuario': usuarioValido,
    }
    return HttpResponse(template.render(context, request))

def loginUser(request):
    template = loader.get_template('FoodFinder/login-comd.html')
    if(request.method == 'POST'):
        nombre = request.POST['usuario']
        clave = request.POST['password']
        user = authenticate(username=nombre, password=clave)
        if user is not None:
            usuario = Usuario.objects.get(nombreUsu=nombre);
            if usuario is not None:
                login(request, user)
                usuario.online = True
                usuario.save()
                if usuario.tipo == "moderador":
                    return redirect('FoodFinder:moderador')
                if usuario.tipo == "admin":
                    return redirect('FoodFinder:admin')
                if usuario.tipo == "cliente":
                    return redirect('FoodFinder:cliente')
                if usuario.tipo=="super-user":
                    return redirect('FoodFinder:super')
        else:
            notice='Ingreso Invalido'
    else:
        notice='none'
    context = {
        'notice':notice
    }
    return HttpResponse(template.render(context, request))

def ajaxMejoresPlatos(request):
    #username = request.GET.get('username', None)
    mejoresPlatos = Platillo.objects.all().order_by('-valoracion')[:5]
    platillos = []
    for plato in mejoresPlatos:
        platillo = {}
        platillo["nombre"] = plato.titulo
        platillo["valoracion"] = plato.valoracion
        platillos.append(platillo)
    data = {
        #'is_taken': User.objects.filter(username__iexact=username).exists()
        'platillos':platillos
    }
    return JsonResponse(data)


    ajaxValorar

def ajaxValorar(request):
    idPlato = request.GET.get("plato_id")
    puntaje = request.GET.get("valor")
    plato = Platillo.objects.get(pk=idPlato)
    total = plato.valoracion + int(puntaje)

    Platillo.objects.filter(pk=idPlato).update(valoracion=total)

    #username = request.GET.get('username', None)
    data = {
        #'is_taken': User.objects.filter(username__iexact=username).exists()
        'platillos':idPlato
    }
    return JsonResponse(data)

def valoracion(request):
    template=loader.get_template('FoodFinder/valoracion.html')
    platillos = Platillo.objects.all()
    platillosDic={}
    for platillo in platillos:
        platillosDic[platillo.comedor.nombre]=platillosDic.get(platillo.comedor.nombre,[])+[platillo]
    try:
        usuario = Usuario.objects.get(nombreUsu=request.user.username)
    except Usuario.DoesNotExist:
        usuario = None
    if usuario is not None:
        usuarioValido = usuario
    else:
        return redirect('FoodFinder:login')
    context = {
        'usuario': usuarioValido,
        "platillosDic": platillosDic
    }
    return  HttpResponse(template.render(context, request))

def denuncia(request):
    template = loader.get_template('FoodFinder/denuncia.html')
    comedores = Comedor.objects.all()
    try:
        usuario = Usuario.objects.get(nombreUsu=request.user.username)
    except Usuario.DoesNotExist:
        usuario = None
    if usuario is not None:
        usuarioValido = usuario
    else:
        return redirect('FoodFinder:login')
    context = {
        'usuario': usuarioValido,
        'comedores':comedores,
        'action': 'Enviar'
    }
    return HttpResponse(template.render(context, request))

def guardarDenuncia(request):
    if (request.POST):
        den = Denuncia()
        den.comedor = request.POST.get('comedor')
        den.fecha_den = request.POST.get('fecha_den')
        den.denuncia = request.POST.get('denuncia')

        den.save()
        messages.success(request, 'Su denuncia se envió correctamente!')
    return redirect('/FoodFinder/denuncia/')

def sesionModerador(request):
    template = loader.get_template('FoodFinder/sesion-moderador.html')

    email_host=settings.EMAIL_HOST_USER
    try:
        usuario = Usuario.objects.get(nombre=request.user.username)
    except Usuario.DoesNotExist:
        usuario = None
    denuncias = Denuncia.objects.all()

    if usuario is not None:
        usuarioValido = usuario
    else:
        return redirect('FoodFinder:login')
    denunciasDic={}
    for den in denuncias:
        denunciasDic[den.comedor]=denunciasDic.get(den.comedor,0)+1
    superAdmin = Usuario.objects.get(nombreUsu="johansito")
    comedores = Comedor.objects.all()

    if(request.method == 'POST'):
        asunto = request.POST.get('subject')
        comedor = request.POST.get('comedor')
        mensaje = request.POST.get('message')
        mensaje_final = "Con respecto al comedor: "+comedor+"\n"+mensaje
        email_envio=[superAdmin.correo]
        send_mail(asunto, mensaje_final, email_host ,email_envio, fail_silently=False)

ComedoresEspol/FoodFinder/templates/FoodFinder/SideBar_base.html
<!Doctype html>
{% load static %}
<html>
	<head>
		<meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
		<title>FoodFinder - {% block titulo %}{% endblock %}</title>
		<link rel="shortcut icon" href="{% static "img/caterin.ico" %}" />
		<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
		<link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
		<link href="{% static "css/estilo.css" %}" rel="stylesheet">
		<link href="{% static "css/est-comed.css" %}" rel="stylesheet">
		{% block extraStyle %}{% endblock %}
	</head>
	<body>
		<nav class="navbar navbar-default sidebar">
			<div id="franja"></div>
			<div class="container-fluid">
				<div class="navbar-header">
					<div id="food-logo" >
						<a href="index.html"><img src="{% static "img/logo-v.png" %}" alt="logo" width="150" /></a>
					</div>
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1" >
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>
				<div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<div class="dropdown">
						  <button class="dropbtn"><span class="glyphicon glyphicon-user"></span> {{usuario.nombreUsu}}</button>
						  <div class="dropdown-content" id="perfil">
						    <a href="{% url 'FoodFinder:cliente'%}">Ver perfil</a>
						  </div>
						</div>

						<li><a href="{% url 'FoodFinder:index'%}">Inicio</a></li>
						<li><a href="{% url 'FoodFinder:galeria'%}">Galeria de Platillos</a></li>
						<li><a href="{% url 'FoodFinder:comedoresC'%}">Comedores Cercanos</a></li>
						<li><a href="{% url 'FoodFinder:comedoresF' %}">Comedores por Facultad</a></li>
						<li><a href="{% url 'FoodFinder:mejoresPlatos' %}">Mejores Platos</a></li>
						<li><a href="{% url 'FoodFinder:about' %}">Nosotros</a></li>
						<li><a href="{% url 'FoodFinder:contacto' %}"> Contacto </a></li>
						<li><a href="{% url 'FoodFinder:historia' %}">Nuestra historia</a></li>
						<li><a href="{% url 'FoodFinder:cerrarSesion'%}"><span class="glyphicon glyphicon-log-out"></span> Cerrar sesión</a></li>
					</ul>
				</div>
			</div>
		</nav>
		<div class="main">
			<div id="encabezado">
				<h1> Conoce tus opciones </h1>
				<h3 class="coolFont"> COMEDORES DE LA ESPOL </h3>
			</div>
			{% block contenido %}{% endblock %}
		</div>
		<script src="{% static "js/jquery-3.2.1.min.js" %}"></script>
		<script src="{% static "js/bootstrap.js" %}"></script>
		<script src="{% static "js/index.js" %}"></script>
		{% block extraScript %}{% endblock %}
	</body>
</html>

ComedoresEspol/FoodFinder/templates/FoodFinder/comedor-usuario.html
{% extends "FoodFinder/SideBar_base.html" %}
{% load static %}
{% block titulo %}Comedore vs Usuarios{% endblock %}
{% block extraStyle %}
<link href="{% static 'css/timeline-style.css' %}" rel="stylesheet">
<link href="{% static 'plugins/chartist/chartist.min.js' %}" rel="stylesheet">
<link href="{% static 'plugins/chartist/chartist.css' %}" rel="stylesheet">
<link href="{% static 'plugins/chartist/chartist.min.css' %}" rel="stylesheet">
{% endblock %}
{% block contenido %}
<div>
<div id="graphic"></div>
</div>
<h2 style="color:black">Los mejores platos de la semana</h2>
<div id="chart_div"></div>
{% endblock %}
{% block extraScript %}
	<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
	<script src="{% static 'js/d3.v3.min.js' %}"></script>
	<script src="{% static 'js/mejoresPlatos.js' %}"></script>
	<script src="{% static 'plugins/chartist/chartist.js' %}"></script>
	<script src="{% static 'plugins/chartist/chartist.min.js' %}"></script>
{% endblock %}

ComedoresEspol/FoodFinder/templates/FoodFinder/comedoresFacultad.html
{% extends "FoodFinder/SideBar_base.html" %}
{% load static %}
{% block titulo %}Comedores por facultad{% endblock %}
{% block extraStyle %}
<link href="{% static 'css/comedores-facultad.css' %}" rel="stylesheet"/>
{% endblock %}
{% block contenido %}
<div id="comedores" class="container">
	<h1 id="titulo">Comedores por facultad</h1>
	{% for comedor in comedores %}
	<div class="comedor col-lg-3 col-sm-3 col-md-4 col-xs-6">
      	<img class="logo-facultad" src="{% static comedor.facultad.logo %}" alt="logo-facultad">
      	<div class="caption">
	        <h3 class="nombre">{{ comedor.nombre }}</h3>
	        <p class="tipo">Tipo: {{ comedor.tipo }}</p>
	        <p class="horario">Horario: {{ comedor.hora_ini }} - {{ comedor.hora_fin }}</p>
	     </div>
        <div class="botoninfo">
	      	<p class="mas-info"><a href="{% url 'FoodFinder:comedor' comedor.id %}" class="btn btn-primary" role="button">Mas Info</a></p>
	    </div>
	</div>
	{% endfor %}
</div>
{% endblock %}

ComedoresEspol/FoodFinder/templates/FoodFinder/sesion-cliente.html
{% extends "FoodFinder/SideBar_base.html" %}
{% load static %}
{% block titulo %}Valoración de los platillos{% endblock %}
{% block extraStyle %}
<link href="{% static "css/sesion-cliente.css" %}" rel="stylesheet">
{% endblock %}
{% block contenido %}
<div class="row">
    <div class="col-lg-6 col-sm-6 col-xs-11" id="informacion">
        <table class="table table-hover">
		    <thead>
		      <tr>
		        <th colspan="2" class="tabla-tit">Información de Contacto</th>
		      </tr>
		    </thead>
		    <tbody>
		      <tr>
		        <td class="comd-info">Nombre</td>
		        <td id="nombreU">{{usuario.nombre}}</td>
		      </tr>
		      <tr>
		        <td class="comd-info">Apellido</td>
		        <td id="apellidoU">{{usuario.apellido}}</td>
		      </tr>
		      <tr>
		        <td class="comd-info">Correo</td>
		        <td id="correoU">{{usuario.correo}}</td>
		      </tr>
		      <tr>
		        <td class="comd-info">Facultad</td>
		        <td id="facultadU">{{ usuario.facultad.nombre }}</td>
		      </tr>
		      <tr>
		      	<td class="comd-info">Rol</td>
		      	<td id="rolU">{{ usuario.rol }}</td>
		      </tr>
		    </tbody>
		  </table>
        <!--a href="{% url 'FoodFinder:modificarUsuario' %}">modificar</a-->

        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editarForm">
            <span class="glyphicon glyphicon-pencil"></span> Editar perfil
        </button>
    </div>
    <div class="col-lg-6 col-sm-6 col-xs-11" id="enlaces">
        <h5>Enlaces</h5>
        <a href="{% url 'FoodFinder:valoracion' %}">Valorar platillos</a><br>
        <a href="{% url 'FoodFinder:denuncia' %}">Enviar una denuncia</a>
    </div>

    <!-- EDITAR FORM MODAL -->
    <div class="modal fade" id="editarForm" tabindex="-100" role="dialog"  aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4>Editar Perfil</h4>
                </div>
                <form>
                    <div class="modal-body">
                        <!-- FORMULARIO -->

                        <div class="form-group">
                            <input class="form-control" type="hidden" id="usuarioId" name="usuarioId" value="{{usuario.id}}"/>
            				<label>Nombre:</label>
                            <input class="form-control" type="text" id="nombre" name="nombre" value="{{usuario.nombre}}" maxlength="16"/>
            			</div>
                        <div class="form-group">
            				<label>Apellido:</label>
            				<input class="form-control" type="text" id="apellido" name="apellido" value="{{usuario.apellido}}" maxlength="16"/>
            			</div>
                        <div class="form-group">
            				<label>Correo:</label>
            				<input class="form-control" type="text" id="correo" name="correo" value="{{usuario.correo}}"/>
            			</div>
                        <div class="form-group">
            				<label>Facultad:</label>
            				<select class="form-control" id="facultad" name="facultad">
            					{% for f in facultades %}
                                {% if f.nombre == usuario.facultad.nombre %}
            					<option value="{{ f.nombre }}" selected>{{ f.nombre }}</option>
                                {% else %}
                                <option value="{{ f.nombre }}">{{ f.nombre }}</option>
                                {% endif %}
            					{% endfor %}
            				</select>
            			</div>
                        <div class="form-group">
            				<label>Rol:</label>
            				<select class="form-control" id="rol" name="rol">
                                {% if "Docente" == usuario.rol %}
                                <option selected>Docente</option>
                                {% else %}
                                <option>Docente</option>
                                {% endif %}
                                {% if "Estudiante" == usuario.rol %}
                                <option selected>Estudiante</option>
                                {% else %}
                                <option>Estudiante</option>
                                {% endif %}
                                {% if "Trabajador" == usuario.rol %}
                                <option selected>Trabajador</option>
                                {% else %}
                                <option>Trabajador</option>
                                {% endif %}
            				</select>
            			</div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="EditarPerfil()">Guardar Cambios</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% block ExtraScript %}
<script src="{% static "js/sesion-cliente.js" %}"></script>
{% endblock %}
{% endblock %}